### ISSUE TITLE
Can we remove "React" as dependency? Goal is 0 deps for security reasons.

### ISSUE THREAD

**Issue by abdelhai** [abdelhai/react-bytesize-icons#8]
Hey @Kilian , I've been outside the JS ecosystem for a while now and not sure how this will work... Any ideas?

https://github.com/abdelhai/react-bytesize-icons/blob/196ea2af0bfd2e7360c5fb8ccdb11fefad3a3056/src/index.js#L1

**Comment by Kilian** [comment]
The reason you want to import React is because it brings JSX in scope, so you need it for the transpilation step. It does not end up in the actual library that you get from NPM, and it's in `devDepencencies` so it won't get installed at the client side as a dependency either (though, of course, React will be a dependency of a consumer project regardless)

**Comment by abdelhai** [comment]
@Kilian thanks for the quick answer. I understand, just checked `package.json` and saw the ´prepublish` script. In this case it's fine since devs will not rely on other dependencies. 👍
